### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by estellyfebiola** [LANDIS-II-Foundation/Extension-Output-Cohort-Statistics#13]
Hi,met this condition while running "Cohort statistic output extension" with "Biomass succession extension". I'm not sure how to solve this error:

```
Internal error occurred within the program:
  Object reference not set to an instance of an object.

Stack trace:
   at Landis.Extension.Output.CohortStats.CohortUtils.GetMinimumAge(ISpecies species, Site site)
   at Landis.Extension.Output.CohortStats.PlugIn.Run()
   at Landis.Model.Run(String scenarioPath, IUserInterface ui)
   at Landis.App.Main(String[] args) in D:\CGAProjects\Rob\LANDIS_FINAL\GitHubRepo\Core-Model-v7\Tool-Console\src\App.cs:line 98
```
thanks

**Comment by rmscheller** [comment]
Estelly,

Please upload a copy of the LANDIS-log.txt file - lots of useful information in there!

**Comment by pevans13** [comment]
Hello. I am also getting the same error as the above post while trying to run "Cohort statistic output extension" with "Biomass succession extension".  I have attached the LANDIS-log.txt file.

Many thanks

[Landis-log.txt](https://github.com/LANDIS-II-Foundation/Extension-Output-Cohort-Statistics/files/10289007/Landis-log.txt)

**Comment by rmscheller** [comment]
Paul,
Please also send your input file for cohort statistics, thanks.

**Comment by pevans13** [comment]
Hi. Please find the cohort statistics input file attached.
Many thanks
[cohorts_grosse.txt](https://github.com/LANDIS-II-Foundation/Extension-Output-Cohort-Statistics/files/10290006/cohorts_grosse.txt)

**Comment by rmscheller** [comment]
Paul,
What succession time step are you using?

**Comment by rmscheller** [comment]
I'm afraid I'm unable to recreate your error.  Could you share the entire scenario (via a shared drive link)?
