### ISSUE TITLE
SiteAgeStats EVEN output seems off.

### ISSUE THREAD

**Issue by jameslamping** [LANDIS-II-Foundation/Extension-Output-Cohort-Statistics#14]
There seems to be an error with the output map being generated for the evenness statistic in SiteAgeStats. Within the active cells the numbers may be correct, but there are minimum values of -2147483648. Attached is one raster output for EVEN from my landscape.
[AGE-EVEN-1.zip](https://github.com/LANDIS-II-Foundation/Extension-Output-Cohort-Statistics/files/11923791/AGE-EVEN-1.zip)

**Comment by jameslamping** [comment]
It seems the eveness stat is not producing correct map outputs. There are no valid data being produced from active cells of my test landscape. This issue is also affecting the use of the eveness stat with biomass hurricane. Issue is submitted there as well.

**Comment by rmscheller** [comment]
James,

I added a default evenness (1.0, the maximum) when only one cohort.  L367:

https://github.com/LANDIS-II-Foundation/Extension-Output-Cohort-Statistics/blob/master/src/CohortUtils.cs

There's a new version and installer for testing:  3.0.4
