### ISSUE TITLE
Disable printing calculated eveness in LANDIS log

### ISSUE THREAD

**Issue by jameslamping** [LANDIS-II-Foundation/Extension-Output-Cohort-Statistics#15]
The newest update is printing the calculated eveness value to the LANDIS log. This slows down the model processing quite a bit and I was hoping we could turn this off. I believe it is the line below in the CohortUtils.cs that needs to be disabled:

![image](https://github.com/LANDIS-II-Foundation/Extension-Output-Cohort-Statistics/assets/40306849/78bf5e2c-3a75-43d5-88a5-39a96c4fafd4)

Thank you!

**Comment by rmscheller** [comment]
James,
I just fixed and committed.  Please test asap.  After this I will be switching to Core v8 and will no longer be able to recompile v7 extensions.  Thanks!
R
